# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rafal/sik/sik2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rafal/sik/sik2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafal/sik/sik2/CMakeFiles /home/rafal/sik/sik2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rafal/sik/sik2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named screen-worms-server

# Build rule for target.
screen-worms-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 screen-worms-server
.PHONY : screen-worms-server

# fast build rule for target.
screen-worms-server/fast:
	$(MAKE) -f CMakeFiles/screen-worms-server.dir/build.make CMakeFiles/screen-worms-server.dir/build
.PHONY : screen-worms-server/fast

#=============================================================================
# Target rules for targets named client-to-server

# Build rule for target.
client-to-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client-to-server
.PHONY : client-to-server

# fast build rule for target.
client-to-server/fast:
	$(MAKE) -f CMakeFiles/client-to-server.dir/build.make CMakeFiles/client-to-server.dir/build
.PHONY : client-to-server/fast

#=============================================================================
# Target rules for targets named crc32

# Build rule for target.
crc32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crc32
.PHONY : crc32

# fast build rule for target.
crc32/fast:
	$(MAKE) -f CMakeFiles/crc32.dir/build.make CMakeFiles/crc32.dir/build
.PHONY : crc32/fast

#=============================================================================
# Target rules for targets named event-parser

# Build rule for target.
event-parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 event-parser
.PHONY : event-parser

# fast build rule for target.
event-parser/fast:
	$(MAKE) -f CMakeFiles/event-parser.dir/build.make CMakeFiles/event-parser.dir/build
.PHONY : event-parser/fast

#=============================================================================
# Target rules for targets named random

# Build rule for target.
random: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 random
.PHONY : random

# fast build rule for target.
random/fast:
	$(MAKE) -f CMakeFiles/random.dir/build.make CMakeFiles/random.dir/build
.PHONY : random/fast

#=============================================================================
# Target rules for targets named connection-manager

# Build rule for target.
connection-manager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connection-manager
.PHONY : connection-manager

# fast build rule for target.
connection-manager/fast:
	$(MAKE) -f CMakeFiles/connection-manager.dir/build.make CMakeFiles/connection-manager.dir/build
.PHONY : connection-manager/fast

#=============================================================================
# Target rules for targets named game-state

# Build rule for target.
game-state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game-state
.PHONY : game-state

# fast build rule for target.
game-state/fast:
	$(MAKE) -f CMakeFiles/game-state.dir/build.make CMakeFiles/game-state.dir/build
.PHONY : game-state/fast

client-to-server.o: client-to-server.cpp.o

.PHONY : client-to-server.o

# target to build an object file
client-to-server.cpp.o:
	$(MAKE) -f CMakeFiles/client-to-server.dir/build.make CMakeFiles/client-to-server.dir/client-to-server.cpp.o
.PHONY : client-to-server.cpp.o

client-to-server.i: client-to-server.cpp.i

.PHONY : client-to-server.i

# target to preprocess a source file
client-to-server.cpp.i:
	$(MAKE) -f CMakeFiles/client-to-server.dir/build.make CMakeFiles/client-to-server.dir/client-to-server.cpp.i
.PHONY : client-to-server.cpp.i

client-to-server.s: client-to-server.cpp.s

.PHONY : client-to-server.s

# target to generate assembly for a file
client-to-server.cpp.s:
	$(MAKE) -f CMakeFiles/client-to-server.dir/build.make CMakeFiles/client-to-server.dir/client-to-server.cpp.s
.PHONY : client-to-server.cpp.s

connection-manager.o: connection-manager.cpp.o

.PHONY : connection-manager.o

# target to build an object file
connection-manager.cpp.o:
	$(MAKE) -f CMakeFiles/connection-manager.dir/build.make CMakeFiles/connection-manager.dir/connection-manager.cpp.o
.PHONY : connection-manager.cpp.o

connection-manager.i: connection-manager.cpp.i

.PHONY : connection-manager.i

# target to preprocess a source file
connection-manager.cpp.i:
	$(MAKE) -f CMakeFiles/connection-manager.dir/build.make CMakeFiles/connection-manager.dir/connection-manager.cpp.i
.PHONY : connection-manager.cpp.i

connection-manager.s: connection-manager.cpp.s

.PHONY : connection-manager.s

# target to generate assembly for a file
connection-manager.cpp.s:
	$(MAKE) -f CMakeFiles/connection-manager.dir/build.make CMakeFiles/connection-manager.dir/connection-manager.cpp.s
.PHONY : connection-manager.cpp.s

crc32.o: crc32.c.o

.PHONY : crc32.o

# target to build an object file
crc32.c.o:
	$(MAKE) -f CMakeFiles/crc32.dir/build.make CMakeFiles/crc32.dir/crc32.c.o
.PHONY : crc32.c.o

crc32.i: crc32.c.i

.PHONY : crc32.i

# target to preprocess a source file
crc32.c.i:
	$(MAKE) -f CMakeFiles/crc32.dir/build.make CMakeFiles/crc32.dir/crc32.c.i
.PHONY : crc32.c.i

crc32.s: crc32.c.s

.PHONY : crc32.s

# target to generate assembly for a file
crc32.c.s:
	$(MAKE) -f CMakeFiles/crc32.dir/build.make CMakeFiles/crc32.dir/crc32.c.s
.PHONY : crc32.c.s

event-parser.o: event-parser.cpp.o

.PHONY : event-parser.o

# target to build an object file
event-parser.cpp.o:
	$(MAKE) -f CMakeFiles/event-parser.dir/build.make CMakeFiles/event-parser.dir/event-parser.cpp.o
.PHONY : event-parser.cpp.o

event-parser.i: event-parser.cpp.i

.PHONY : event-parser.i

# target to preprocess a source file
event-parser.cpp.i:
	$(MAKE) -f CMakeFiles/event-parser.dir/build.make CMakeFiles/event-parser.dir/event-parser.cpp.i
.PHONY : event-parser.cpp.i

event-parser.s: event-parser.cpp.s

.PHONY : event-parser.s

# target to generate assembly for a file
event-parser.cpp.s:
	$(MAKE) -f CMakeFiles/event-parser.dir/build.make CMakeFiles/event-parser.dir/event-parser.cpp.s
.PHONY : event-parser.cpp.s

game-state.o: game-state.cpp.o

.PHONY : game-state.o

# target to build an object file
game-state.cpp.o:
	$(MAKE) -f CMakeFiles/game-state.dir/build.make CMakeFiles/game-state.dir/game-state.cpp.o
.PHONY : game-state.cpp.o

game-state.i: game-state.cpp.i

.PHONY : game-state.i

# target to preprocess a source file
game-state.cpp.i:
	$(MAKE) -f CMakeFiles/game-state.dir/build.make CMakeFiles/game-state.dir/game-state.cpp.i
.PHONY : game-state.cpp.i

game-state.s: game-state.cpp.s

.PHONY : game-state.s

# target to generate assembly for a file
game-state.cpp.s:
	$(MAKE) -f CMakeFiles/game-state.dir/build.make CMakeFiles/game-state.dir/game-state.cpp.s
.PHONY : game-state.cpp.s

random.o: random.cpp.o

.PHONY : random.o

# target to build an object file
random.cpp.o:
	$(MAKE) -f CMakeFiles/random.dir/build.make CMakeFiles/random.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i

.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	$(MAKE) -f CMakeFiles/random.dir/build.make CMakeFiles/random.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s

.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	$(MAKE) -f CMakeFiles/random.dir/build.make CMakeFiles/random.dir/random.cpp.s
.PHONY : random.cpp.s

screen-worms-server.o: screen-worms-server.cpp.o

.PHONY : screen-worms-server.o

# target to build an object file
screen-worms-server.cpp.o:
	$(MAKE) -f CMakeFiles/screen-worms-server.dir/build.make CMakeFiles/screen-worms-server.dir/screen-worms-server.cpp.o
.PHONY : screen-worms-server.cpp.o

screen-worms-server.i: screen-worms-server.cpp.i

.PHONY : screen-worms-server.i

# target to preprocess a source file
screen-worms-server.cpp.i:
	$(MAKE) -f CMakeFiles/screen-worms-server.dir/build.make CMakeFiles/screen-worms-server.dir/screen-worms-server.cpp.i
.PHONY : screen-worms-server.cpp.i

screen-worms-server.s: screen-worms-server.cpp.s

.PHONY : screen-worms-server.s

# target to generate assembly for a file
screen-worms-server.cpp.s:
	$(MAKE) -f CMakeFiles/screen-worms-server.dir/build.make CMakeFiles/screen-worms-server.dir/screen-worms-server.cpp.s
.PHONY : screen-worms-server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... screen-worms-server"
	@echo "... client-to-server"
	@echo "... crc32"
	@echo "... event-parser"
	@echo "... random"
	@echo "... rebuild_cache"
	@echo "... connection-manager"
	@echo "... game-state"
	@echo "... client-to-server.o"
	@echo "... client-to-server.i"
	@echo "... client-to-server.s"
	@echo "... connection-manager.o"
	@echo "... connection-manager.i"
	@echo "... connection-manager.s"
	@echo "... crc32.o"
	@echo "... crc32.i"
	@echo "... crc32.s"
	@echo "... event-parser.o"
	@echo "... event-parser.i"
	@echo "... event-parser.s"
	@echo "... game-state.o"
	@echo "... game-state.i"
	@echo "... game-state.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... screen-worms-server.o"
	@echo "... screen-worms-server.i"
	@echo "... screen-worms-server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

